TICK-0004 created DAOS interfaces with class.
DanMedl/com.atb pull request #8
Opened 2024-02-07 20:03 UTC by DanMedl

TICK-0004 created DAOS interfaces with class.

2024-02-08 15:36 UTC, Shaff3004 requested changes

2024-02-08 21:41 UTC, DanMedl commented on com.atb/src/main/java/daos/CategoryDao.java
> +    Category getCategoryByCode(String code);
done

2024-02-08 21:41 UTC, DanMedl commented on com.atb/src/main/java/daos/DefaultCategoryDao.java
> +    private Map<String, Category> categoryStorage = new HashMap<>();
done

2024-02-08 21:41 UTC, DanMedl commented on com.atb/src/main/java/daos/DefaultCategoryDao.java
> +    }
done

2024-02-08 21:41 UTC, DanMedl commented on com.atb/src/main/java/daos/DefaultCategoryDao.java
> +        if (categoryStorage.containsKey(category.getCode())) {
done

2024-02-08 21:41 UTC, DanMedl commented on com.atb/src/main/java/daos/DefaultCategoryDao.java
> +
done

2024-02-08 21:41 UTC, DanMedl commented on com.atb/src/main/java/daos/DefaultProductDao.java
> +package daos;
done

2024-02-08 21:44 UTC, DanMedl commented on com.atb/src/main/java/daos/DefaultProductDao.java
> +        return productStorage.get(id);
I delete this method but I had to delete field in ProductDao class. Is it correct? 
All method should be override when we implement this interface and it just couldn’t went through IDEA complier. 
Please advise

2024-02-09 10:04 UTC, Shaff3004 commented on com.atb/src/main/java/com/atb/daos/DefaultCategoryDao.java
> +package com.atb.daos;
for implementation classes package should be com.atb.daos.impl

2024-02-09 10:04 UTC, Shaff3004 commented on com.atb/src/main/java/com/atb/daos/DefaultCategoryDao.java
> +
remove empty line

2024-02-09 10:05 UTC, Shaff3004 commented on com.atb/src/main/java/com/atb/daos/DefaultProductDao.java
> +package com.atb.daos;
the same here: com.atb.daos.impl

2024-02-09 10:05 UTC, Shaff3004 commented on com.atb/src/main/java/com/atb/daos/DefaultProductDao.java
> +import com.atb.dtos.Category;
Are you sure you need that import in this class?

2024-02-09 10:08 UTC, Shaff3004 commented on com.atb/src/main/java/com/atb/daos/DefaultProductDao.java
> +    private Map<String, Product> productStorage = new HashMap<>();
put empty line between class and productStorage

2024-02-11 20:01 UTC, DanMedl commented on com.atb/src/main/java/com/atb/daos/DefaultCategoryDao.java
> +
done

2024-02-11 20:01 UTC, DanMedl commented on com.atb/src/main/java/com/atb/daos/DefaultProductDao.java
> +import com.atb.dtos.Category;
done

2024-02-11 20:01 UTC, DanMedl commented on com.atb/src/main/java/com/atb/daos/DefaultProductDao.java
> +    private Map<String, Product> productStorage = new HashMap<>();
done

2024-02-11 20:03 UTC, merged